In [2]:
import cv2
import numpy as np

# colors
colors = {
    'white': 255,
    'light_gray': 230,
    'gray': 170,
    'dark_gray': 64,
    'black': 0,
}

In [3]:
# read the image
rgb_image = cv2.imread('images/firat.jpeg')

# convert the image to grayscale
gray_image = cv2.cvtColor(rgb_image, cv2.COLOR_BGR2GRAY)

print(gray_image)
print(gray_image.shape)

[[143 143 143 ...  59  57  57]
 [142 143 143 ...  59  58  57]
 [141 143 144 ...  59  58  57]
 ...
 [109 113 119 ...  51  52  52]
 [109 113 119 ...  51  51  51]
 [109 113 119 ...  51  52  52]]
(629, 629)


In [4]:
# canny edge detection
edges = cv2.Canny(gray_image, 40, 90)
edges = cv2.bitwise_not(edges)

cv2.imshow('edges', edges)

In [5]:
# This code section removes blurry backgrounds

# create a padded version of the Canny edge image
kernel_size = (150, 150)
padded_canny = cv2.copyMakeBorder(edges, kernel_size[0]//2, kernel_size[0]//2,
                                  kernel_size[1]//2, kernel_size[1]//2, cv2.BORDER_CONSTANT, value=0)

# create an output image
output_image = np.zeros_like(gray_image)

# iterate over each pixel in the original image
for i in range(gray_image.shape[0]):
    for j in range(gray_image.shape[1]):
        # get the kernel region around the pixel
        kernel_region = padded_canny[i:i+kernel_size[0], j:j+kernel_size[1]]
        # if min value is 0, set the output pixel to the original value
        if np.min(kernel_region) == 0:
            output_image[i, j] = gray_image[i, j]
        else:
            # else, set the output pixel to grey
            output_image[i, j] = 224

# remove the padding
output_image = output_image[kernel_size[0]//2:-kernel_size[0]//2, kernel_size[1]//2:-kernel_size[1]//2]

cv2.imshow('output_image', output_image)

# key = cv2.waitKey(0)

# # Check the pressed key
# if key == ord('q'):
#     # If 'q' is pressed, close the window and exit
#     cv2.destroyAllWindows()

In [5]:
# map each pixel of the gray image to the closest color
output_image = gray_image

gray_filter = np.zeros_like(output_image)
for i in range(output_image.shape[0]):
    for j in range(output_image.shape[1]):
        if output_image[i, j] <= 42:
            gray_filter[i, j] = colors['black']
        elif output_image[i, j] <= 100:
            gray_filter[i, j] = colors['dark_gray']
        elif output_image[i, j] <= 160:
            gray_filter[i, j] = colors['gray']
        elif output_image[i, j] <= 230:
            gray_filter[i, j] = colors['light_gray']
        else:
            gray_filter[i, j] = colors['white']

# display the image
cv2.imshow('gray_image', gray_image)
cv2.imshow('gray_filter', gray_filter)

key = cv2.waitKey(0)

# check the pressed key
if key == ord('q'):
    # if 'q' is pressed, close the window and exit
    cv2.destroyAllWindows() 